# -*- coding: utf-8 -*-
"""
Created on Mon Jun 28 12:21:03 2021

@author: gqmli
"""

import nglview as ngl
def compare(traj, num, *num_list):
    """
    Add several frames to the same plot to compare the structural difference

    Parameters
    ----------
    traj : MD trajectory loaded by mdtraj
        The target trajectory for analysis
    num : int
        Add the first frame #
    *num_list : int
        One or more frame # to compare

    Returns
    -------
    Plot generated by nglview

    """
    view = ngl.show_mdtraj(traj[num])
    for frame in num_list:
        view.add_trajectory(traj[frame])
    return view