from bokeh.plotting import figure, show
from bokeh.io import output_notebook

def dimrect(Method, array):
    """
    Visualize the results from dimensionality reduction
    Only applicable for dimension reduced to 2D

    Parameters
    ----------
    Method : String
        Specify the algorithm for dimensionality reduction, used for the title of the plot
    array : Numpy array, shape=(num of instances, 2)
        The array generated by dimensionality reduction, set n_components=2

    Returns
    -------
    None.

    """
    # check for dimensionality
    if array.shape[-1]==2:        
        x = array[:, 0].reshape(len(array), )
        print(x)
        y = array[:, 1].reshape(len(array), )
        p = figure(title=Method, x_axis_label='x', y_axis_label='y')
        p.circle(x, y)
        output_notebook()
        show(p)
    else:
        print('Sorry, only dimension reduced to 2D accepted.')
