# -*- coding: utf-8 -*-
"""
Created on Mon Jun 28 12:21:03 2021

@author: gqmli
"""

import nglview as ngl
import mdtraj as md
class Visualization():
    def _init_(self, traj_file, top_file):
        self.traj_file = traj_file
        self.top_file = top_file
        self.traj = md.load(traj_file, top=top_file)
        
    def ball_and_stick(self):
        """
        Show the ball and stick structure of the atom on screen
        
        Parameters
        ----------
        None.

        Returns
        -------
        Plot generated by nglview

        """
        return ngl.show_mdtraj(self.traj)
        
    def compare(self, num, *num_list):
        """
        Add several frames to the same plot to compare the structural difference
    
        Parameters
        ----------
        num : int
            Add the first frame #
        *num_list : int
            One or more frame # to compare
    
        Returns
        -------
        Plot generated by nglview
    
        """
        view = ngl.show_mdtraj(self.traj[num])
        for frame in num_list:
            view.add_trajectory(self.traj[frame])
        return view